### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [meshtastic/Meshtastic-Android#829]
My APK scanner just got some extra checks implemented recently, and on today's update reported:

    ! repo/com.geeksville.mesh_30219.apk declares sensitive permission(s): android.permission.BLUETOOTH_SCAN android.permission.ACCESS_FINE_LOCATION android.permission.ACCESS_COARSE_LOCATION android.permission.ACCESS_BACKGROUND_LOCATION android.permission.CAMERA

Could you please clarify what those permissions are needed for? I mean, some can be guessed if one's a bit familiar what the app does, but not everyone is :wink: 

Thanks in advance!

**Comment by andrekir** [comment]
Hello @IzzySoft !

[![Intro](https://meshtastic.org/img/introduction/lora-topology-2.png)](https://meshtastic.org/docs/introduction)

Meshtastic uses [inexpensive LoRa radios](https://meshtastic.org/docs/hardware/devices/) for long range off-grid communications.

- The app connects to radios via Bluetooth, WiFi or Serial.
- Radios without GPS can use Android's GPS.
- QR Codes containing configs and channel encryption can be shared using the camera.

**All runtime permissions are optional.**

Short video explaining location permissions:

[![Watch the video](https://img.youtube.com/vi/6Mt7AsH_LSc/hqdefault.jpg)](https://youtu.be/6Mt7AsH_LSc)

**Comment by IzzySoft** [comment]
Thanks, added to the allow-list then:

```yaml
      android.permission.BLUETOOTH: needed to connect to radios via Bluetooth
      android.permission.BLUETOOTH_ADMIN: needed to automatically pair detected radios
      android.permission.BLUETOOTH_CONNECT: needed to automatically connect to radios via Bluetooth
      android.permission.BLUETOOTH_SCAN: needed to find radios to connect to via Bluetooth
      android.permission.ACCESS_FINE_LOCATION: needed so radios without GPS can use Android’s GPS
      android.permission.ACCESS_COARSE_LOCATION: needed so radios without GPS can use Android’s location service
      android.permission.ACCESS_BACKGROUND_LOCATION: needed to provide radios without GPS with Android’s location while the app is in background
      android.permission.CAMERA: needed by the integrated QR Code scanner
```

> All runtime permissions are optional

… since Android 6. Your app still supports Android 5 :wink: And even being optional: it's good to know in advance, builds up trust :smile: So if you want to cross-check (and maybe suggest some adjustments):

![image](https://github.com/meshtastic/Meshtastic-Android/assets/6781438/9240ecbb-1052-46f6-a86a-3308d2ec93d7)

Oh yeah: `DEPENDENCY_INFO_BLOCK`. A BLOB only readable by Google (as it's encrypted with their public key) and thus useless for everybody else. Want to get rid of that?

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.
